name: HoutianPlugin
main: xyz.houtian17.Plugin
version: 0.2
description: Houtian's Plugin
author: Houtian

commands:
  hello:
    description: Basic command that returns "Hello" to the players who sends it
    usage: /hello
  tps:
    description: Teleport player to spawn
    usage: /tps
  se:
    description: give you a zombie
    usage: /se